name: Test CICD
on:
  push:
    branches: [main]
jobs:
  test-package:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Install python"
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          architecture: 'x64'
          cache: 'pip'
      - name: "Install project dependencies"
        run: pip install -r requirements.txt
      - name: "Run tests"
        run: pytest
      - name: "Archive pytest results"
        uses: actions/upload-artifact@v2
        if: ${{!cancelled()}}
        with:
          name: pytest-report
          path: pytest-report.html
  build-and-push-docker:
    needs: test-package
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v2
      - name: "Set up Docker BuildX"
        uses: docker/setup-buildx-action@v2
      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.ACTOR }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build and push docker image"
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ github.REPOSITORY }}:${{ github.REF_NAME }}
          labels: run_number=${{ github.RUN_NUMBER }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
